### PR TITLE
Verse calculus resources.

### PR DESCRIPTION
**Pull request by tkersey**
Adding a couple of resources around the Verse calculus.

### CODE REVIEW

**Comment by spilth** [comment]
Hey Tim,

Thank you for the PR!

It has me wondering if I should narrow the repo name. I was imagining this as a list of resources for people working with Verse, specifically inside of Unreal Engine for Fortnite and potentially as a first time programmer. I'm worried the scientific paper/talk is on the heavy side. But given the current name of the repo/list, it should be fair game.

I'm wondering if the deeper dives like these should be in a dedicated section. What do you think?

**Comment by tkersey** [comment]
@spilth Yeah I wasn't certain that these links fit your intent. A dedicated section makes sense. A suggestion: `#Technical Foundations` or something to that effect. Also feel free not to include them at all.

**Comment by spilth** [comment]
@tkersey `Technical Foundations` sounds good to me!

**Review by spilth — APPROVED** [review]
Thank you!

**Pull request merged**
